name: "CICD Workflow"
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.6
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: learning_management_system_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    strategy:
      fail-fast: true
    env:
      RAILS_ENV: test
      RACK_ORIGINS: "*"
      DATABASE_URL: "postgres://postgres:postgres@localhost/learning_management_system_test?encoding=utf8&pool=5&timeout=5000"
      CDN_HOST: "http://localhost:3001"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.3"
      - name: Install gems
        run: bundle install
      - name: Setup test database
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run RSpecs
        run: bundle exec rspec spec/
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Install gems
        run: bundle install
      - name: Run rubocop
        run: rubocop
