version: "3.9"
services:
  database:
    image: postgres:13.8
    restart: always
    ports:
      - "5433:5432"
    environment:      
      POSTGRES_PASSWORD: postgres       
      POSTGRES_USER: postgres       
      POSTGRES_DB: learning_management_system  
      POSTGRES_HOST: localhost
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash -c "rails db:environment:set RAILS_ENV=development && bundle exec rake db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    environment:      
      DATABASE_URL: postgres://postgres:postgres@database:5432/learning_management_system?encoding=utf8&pool=5&timeout=5000   
    volumes:
      - .:/app
    depends_on:
      - database

volumes:
  postgres: